# Generated by Django 5.1.6 on 2025-03-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('descuento_app', '0002_remove_discount_used_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutdiscount',
            name='state',
            field=models.BooleanField(default=True),
        ),
    ]
